spring:
  dubbo:
    application:
      name: timetravel-gaea
    registry:
      server: zkRegistry
      protocol: zookeeper
      address: www.zhuoqitech.com.cn:2181
      file: ${user.home}/.dubbo/8081-timetravel-gaea.cache
      cluster: failfast
    protocol:
      port: 18081
      payload: 16777216
    provider:
      timeout: 6000
      retries: 0
      delay: -1
      group:
      package: com.zhuoqitech.timetravel.gaea.biz.service.facade


  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://118.31.123.186:3306/timetravel?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: zhuoqidb@123
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,slf4j,config
    max-active: 100
    initial-size: 1
    max-wait: 60000
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 50
    max-pool-prepared-statement-per-connection-size: 20
  redis:
    host: 47.110.85.51
    port: 6379
    timeout: 6000
    pool:
      max-active: 200
      max-idle: 100
      min-idle: 30
      max-wait: 100
    password: subhuti@123


  http:
    encoding:
      charset: utf-8
  mvc:
    favicon:
      enabled: false
    view:
      prefix: /view/
      suffix: .html

#logging:
  #file: /data/logs/apps/gsq.log
  #level:
    #com.zhuoqitech.timetravel.dal.mapper: DEBUG
    #org.springframework.web: INFO
  #config: log4j2-spring.xml

fastdfs:
  # 查看文件的服务器地址
  viewServerUrl: http://fastdfs.zhuoqitech.com.cn

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mybatis/mapping/*/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zhuoqitech.timetravel.dal
  typeEnumsPackage:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    #key-generator:
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
#    sql-injector:
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
#    meta-object-handler:
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    #sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

timetravel:
  constant:
#    loginUrl: http://localhost:8080/loginPage
    loginUrl: http://market.daisibiz.com/loginPage
    smsAccesskey: oQZjmIN33kH8OqJG
    smsSecret: cclXXcDTKceXXnn2AEwgzOgZat7QHNlM
    smsSendUrl: http://api.1cloudsp.com/api/v2/send
    enableSms: 0
